### ISSUE TITLE
Would you guess this would work with Joomla 1.5?

### ISSUE THREAD

**Issue by DarwinJS** [davetcc/hugojoomla#8]
I know you can't make any guarantees - any guesses?

**Comment by davetcc** [comment]
Hi there,

I think as it stands it would fail on the tag parse stage as 1.5 didn't
have tags. Let me take a look a feasibility later to make it universal and
feed back on it.

Thanks
Dave


On 31 Jan 2017 12:37 p.m., "Darwin" <notifications@github.com> wrote:

I know you can't make any guarantees - any guesses?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/davetcc/hugojoomla/issues/8>, or mute the thread

**Comment by davetcc** [comment]
After a quick read online about 1.5 database structure I think it may work to some extent if we were to comment out the line that calls the loadTags method in the converter class. I can't say for sure if there will be issues as columns could be missing.

Further on 1.5 there were sections as well as categories and this could be problematic. I can try and commit and build a version very soon with optional tags processing but in the mean time you could try commenting the load tags line out.

**Comment by DarwinJS** [comment]
Thanks for checking it out!

I saw something at a another site that implied I could use Jekyll's native Joomla 1.5 converter and simply use the output folder in Hugo.  Does that make sense?

**Comment by davetcc** [comment]
That will quite possibly work, although I've not tried it myself. Whichever way you go you'll only get about 90% of the way automatically anyway, so it's worth a go.

I'll try and get around to making the tags optional anyway. If still available, I can I'll try it with one of my old joomla backups afterwards I think they may be 2.x.
